#!/usr/bin/env bash

# Generate a tags file from the project root, excluding some common things
# which tend to not yield very helpful tags.

set -e

trap "rm -f .git/tags.$$" EXIT

ctags \
	-f .git/tags.$$ \
	--tag-relative \
	--recurse \
	--exclude=.git \
	--exclude=tmp \
	--exclude=coverage \
	--languages=-sql

mv .git/tags.$$ .git/tags
